### ISSUE TITLE
Prevent Google from Indexing the site

### ISSUE THREAD

**Issue by DatChoob** [DatChoob/FishLabManagerUI#34]
This application should be hidden and not found from google.
This is to prevent bots from crawling the site.

Some research proposes adding a robot.txt that when google crawls our site, tells google to not index the site.
https://moz.com/learn/seo/robotstxt

Maybe we don't need this at all. It just a nice to have.

**Comment by nosas** [comment]
This is nice to have, and I believe we should implement it, _but_ Coleman said he liked having the website show up on Google.

**Comment by DatChoob** [comment]
Yeah. Looks like this wont be needed. Closing issue
