### ISSUE TITLE
User ID field in Tank Management Details page missing required asterisk

### ISSUE THREAD

**Issue by nosas** [DatChoob/FishLabManagerUI#45]
_Bug Description_
- When adding/modifying a tank, the User ID field is missing the required asterisk. 
- Form does not notify user when User ID is not selected upon adding a new tank (except for a 500 error in the console)

_Expected Behavior_
- User ID field has the required asterisk and notifies the user it's a required field when adding a new tank.

_Screenshots_
![image](https://user-images.githubusercontent.com/12710033/48242234-2081b500-e38f-11e8-9632-64286d81edd8.png)

**Comment by PotatoCoder3000** [comment]
FIxed.
